config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'top#index'

  resources :photos

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name:     auth.extra.raw_info.name,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url:   auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name:     auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  # omniauthでサインアップしたアカウントのユーザ情報の変更出来るようにする
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

  #deviseのストロングパラメーターにカラム追加するメソッドを定義
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
    devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.order('updated_at DESC')
  end

  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: '作成しました！' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_path, notice: '更新しました！' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: '削除しました！' }
    end
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :content, :image, :user_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

  def destroy
    # ユーザーに紐付く投稿の削除
    Photo.where(user_id:current_user.id).delete_all
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroPhotos</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.3/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container is-fluid">
      <nav class="navbar">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <img src="<%= asset_path "logo.png" %> ">
          </a>
        </div>
        <div class="navbar-menu">
          <div class="navbar-start">
          </div>
          <div class="navbar-end">
            <%= link_to new_photo_path, class: "navbar-item" do %>
              <span class="icon">
                <i class="fa fa-paper-plane-o"></i>
              </span>
              新規投稿
            <% end %>
            <%= link_to photos_path, class: "navbar-item" do %>
              <span class="icon">
                <i class="fa fa-photo"></i>
              </span>
              投稿一覧
            <% end %>
            <% if user_signed_in? %>
              <%= link_to edit_user_registration_path, class: "navbar-item" do %>
                <span class="icon">
                  <i class="fa fa-user-o"></i>
                </span>
                ユーザー情報
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "navbar-item" do %>
                <span class="icon">
                  <i class="fa fa-sign-out"></i>
                </span>
                サインアウト
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "navbar-item" do %>
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                ログイン
              <% end %>
              <%= link_to new_user_registration_path, class: "navbar-item" do %>
                <span class="icon">
                  <i class="fa fa-user-plus"></i>
                </span>
                新規登録
              <% end %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      <div class="columns is-mobile">
        <div class="column is-11 is-offset-1">
          <br>
          <%= yield %>
          <br>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>MicroPhotos</strong> by <a href="https://github.com/yshr446">Yoshihiro Saito</a>. The source code is licensed
          <a href="https://diveintocode.jp/">DIC</a>
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/photos/_form.html.erb
<br>
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
        <% @photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title,"タイトル", class:"label" %>
    <%= f.text_field :title, class:"input" %>
  </div>
  <div class="field">
    <%= f.label :content,"内容", class:"label" %>
    <%= f.text_field :content, class:"input" %>
  </div>
  <div class="field">
    <%=f.label :image,"画像", class:"label" %>
    <%= f.file_field :image, class:"input"%>
  </div>
  <div class="actions">
    <%= f.submit "登録", class: "button is-primary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="columns is-mobile">
  <div class="column is-half is-offset-one-quarter">
    <%= render 'form' %>
  </div>
</div>

app/views/photos/index.html.erb
<div class="columns is-mobile">
  <div class="column is-half is-offset-one-quarter">
    <% if notice %>
      <article class="message is-primary">
        <div class="message-body">
          <p><%= notice %></p>
        </div>
      </article>
    <% end %>
    <% if alert %>
      <article class="message is-danger">
        <div class="message-body">
          <p><%= alert %></p>
        </div>
      </article>
    <% end %>
    <% @photos.each do |photo| %>
      <div class="card">
        <div class="card-image">
          <figure class="image is-480x480">
            <% if photo.image.blank? then %>
              <img src="<%= asset_path "no_image.png" %> ">
            <% else %>
              <img src="<%= photo.image %>" alt="Image">
            <% end %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <%= profile_img(User.find(photo.user_id)) %>
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= photo.title %></p>
              <p class="subtitle is-6"><%= User.find_by(id:photo.user_id).name %></p>
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <%= link_to '詳細', photo ,class: "card-footer-item"%>
        </div>
      </footer>
      <br>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="columns is-mobile">
  <div class="column is-half is-offset-one-quarter">
    <%= render 'form' %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="columns is-mobile">
  <div class="column is-half is-offset-one-quarter">
    <div class="card">
      <div class="card-image">
        <figure class="image is-480x480">
          <% if @photo.image.blank? then %>
            <img src="<%= asset_path "no_image.png" %> ">
          <% else %>
            <img src="<%= @photo.image %>" alt="Image">
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <%= profile_img(User.find(@photo.user_id)) %>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= @photo.title %></p>
            <p class="subtitle is-6"><%= User.find_by(id:@photo.user_id).name %></p>
          </div>
        </div>
        <div class="content">
          <p><big><%= @photo.content %></big></p>
          <p><small><%= @photo.updated_at %></small></p>
        </div>
      </div>
      <footer class="card-footer">
        <%= link_to '編集', edit_photo_path(@photo) ,class: "card-footer-item"%>
        <%= link_to '削除', @photo, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "card-footer-item"%>
      </footer>
    </div>
  </div>

app/views/top/index.html.erb
<% if notice %>
  <article class="message is-primary">
    <div class="message-body">
      <p><%= notice %></p>
    </div>
  </article>
<% end %>
<section class="hero is-primary is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Welcome to MicroPhotos
      </h1>
    </div>
  </div>
</section>
<div class="columns">
  <div class="column">
    <div class="column">
      <img src="<%= asset_path "iphone.png" %> ">
    </div>
  </div>
  <% if !user_signed_in? %>
    <div class="column">
      <div class="column is-half">
        <%= link_to '　　　新規登録　　　', new_user_registration_path,class: "button is-large is-warning"%>
      </div>
      <div class="column is-half">
        <%= link_to '　　　ログイン　　　', new_user_session_path,class: "button is-large is-danger"%>
      </div>
      <div class="column is-half">
        <%= link_to "Sign in with Facebook", omniauth_authorize_path(:user, :facebook),class: "button is-large is-info" %>
      </div>
      <div class="column is-half">
        <%= link_to "Sign in with Twitter", omniauth_authorize_path(:user, :twitter),class: "button is-large is-primary" %>
      </div>
    </div>
  <% end %>
</div>
</div>